### ISSUE TITLE
Upgrading bot

### ISSUE THREAD

**Issue by Calanchi96** [6b6576696e/maple-bot#14]
Hi Kevin,

I'm a developer but i'm kinda new to python, i am willing to upgrade your bot with some gui and some fetures.
is there any way to reach out to you?

Thank you in advance

**Comment by 6b6576696e** [comment]
Hi Calanchi96,

Thank you for the offer but I don't plan on updating this program anymore. Feel free to modify or use the code. If you would like to contact me, I am active on Discord. I can add you if you provide your username and tag.

**Comment by Calanchi96** [comment]
Hello Kevin,

Thank you anyway for the reply :), here's my discord name and tag. Croccaroc#0628

**Comment by NhatL** [comment]
Hi Kevin,

Would you be able to add me too? 1235#6709. Just wanted to ask some questions about the coordinates

**Comment by 6b6576696e** [comment]
Hi Calanchi96,

The Discord username and tag combination you have provided is invalid.

**Comment by Calanchi96** [comment]
Sorry missed a zero
Croccaroc#0628
