### ISSUE TITLE
About maple bot...

### ISSUE THREAD

**Issue by leesumin1** [6b6576696e/maple-bot#16]
There's something I want to talk about maple bot. Can I know Discord or other SNS id?

**Comment by 6b6576696e** [comment]
Hi leesumin1,

I will add you if you comment your Discord username and tag.

**Comment by leesumin1** [comment]
It's Samurai#2948

**Comment by leesumin1** [comment]
> 안녕하세요 leesumin1님
> 
> Discord 사용자 이름과 태그를 댓글로 남겨주시면 추가하겠습니다.

Samurai#2948
