### ISSUE TITLE
Coords mismatching between PLAYER and RUNE

### ISSUE THREAD

**Issue by zionttsang** [6b6576696e/maple-bot#2]
Hi there. Thanks for your project.
While using, the botting part is OK. But when it comes to rune solve, there is always has some mismatching happens at the Y axis with the PLAYER and the RUNE.
For example, when the PLAYER and RUNE are in the same horizon platform, the Y coord value of the RUNE is always higher (27 pixel higher ) than the PLAYER. 

I have check the code and found that the locating function is same.  (In game.py, using location function.)
But I can not figure it out that why the locating result on Y axis is always a big gap.

**Comment by 6b6576696e** [comment]
Hi zionttsang,

Please make sure you are on 800x600 resolution, the bot will has only been tested for this window application size.

If the `locate` function in`game.py` is able to accurately determine your player location but not the rune location, it may have to do with the colors in your search region. The implementation of `locate` does not use template matching and instead relies on finding the index of every matching color pixel and taking an average of their positions. As a result, if there are extra colors in your search region that have the same BGRA value as RUNE_BGRA, this will mess up the calculation.

**Comment by zionttsang** [comment]
Thanks for your reply~
I do change the resolution of the game window. 
As you explained, the BRGA value may be the main reason. I will try as you mentioned about re-confirming the BRGA value.

Thanks again~

**Comment by 6b6576696e** [comment]
You're welcome! I would like to add that I had this exact problem in Lachelein. The mini-map background and colors have the same BGRA values as runes. Good luck!
